// <auto-generated />
using System;
using InactiviteRoleRemover;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InactiviteRoleRemover.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210204013257_nicknames")]
    partial class nicknames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InactiviteRoleRemover.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleIdsToRestore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80c640b5-2080-4da0-8de3-b7f8c07d3271"),
                            DiscordId = 123m,
                            LastActivity = new DateTime(2021, 2, 3, 20, 32, 57, 238, DateTimeKind.Local).AddTicks(3703)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
